version: "3.5"

services:
    node-api:
        container_name: sp-smalltalk-app
        restart: always
        ports:
            - "3000:3000"
            - "8070:8070"
        image: sp-smalltalk-node-js
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        command: "npm start"
        networks:
            - sp-network

    mongo-db:
        image: mongo
        container_name: sp-smalltalk-mongodb
        ports:
            - "27017-27019:27017-27019"
        networks:
            - sp-network

networks:
    sp-network:
        name: sp-network
        driver: bridge
